# Default titles for the reviews
DEFAULT_TITLE = [
    "Great Product!",
    "Highly Recommend",
    "Very Satisfied",
    "Exceeded Expectations",
    "Will Buy Again",
    "Fantastic Quality",
    "Worth Every Penny",
    "Impressive Results",
    "Top Notch",
    "Five Stars",
    "Amazing Experience",
    "Best Purchase Ever",
    "Superb Quality",
    "Absolutely Love It",
    "Highly Effective",
    "Outstanding Product",
    "Remarkable Value",
    "Unmatched Quality",
    "Perfect Choice",
    "Incredible Results",
    "Exceptional Service",
    "Unbelievable Quality",
    "A Must-Have",
    "Top Quality",
    "Best in Class",
    "Phenomenal Product",
    "Super Satisfied",
    "Highly Impressed",
    "Fantastic Experience",
    "Unparalleled Quality",
    "Excellent Purchase",
    "Very Impressed",
    "Highly Satisfied",
    "Top Recommendation",
    "Great Value",
    "Superb Experience",
    "Outstanding Quality",
    "Highly Praised",
    "Very Happy",
    "Top Choice"
]

# Theme strings for the review text
THEME_STRINGS = {
    "Quality": "The quality of this product is outstanding.",
    "Value": "This product offers great value for the price.",
    "Effectiveness": "I found this product to be highly effective.",
    "Ease of Use": "This product is very easy to use.",
    "Taste": "The taste of this product is excellent.",
    "Packaging": "The packaging is very secure and attractive.",
    "Ingredients": "The ingredients used are of high quality.",
    "Customer Service": "Customer service was very helpful and responsive.",
    "Shipping": "Shipping was fast and the product arrived on time.",
    "Results": "I am very pleased with the results I got from this product.",
    "Durability": "This product is very durable and long-lasting.",
    "Design": "The design of this product is sleek and modern.",
    "Comfort": "This product is very comfortable to use.",
    "Performance": "The performance of this product is top-notch.",
    "Reliability": "This product is very reliable.",
    "Safety": "This product is very safe to use.",
    "Convenience": "This product is very convenient.",
    "Appearance": "The appearance of this product is very appealing.",
    "Functionality": "This product has great functionality.",
    "Innovation": "This product is very innovative.",
    "Affordability": "This product is very affordable.",
    "Versatility": "This product is very versatile.",
    "Eco-Friendly": "This product is eco-friendly.",
    "User-Friendly": "This product is user-friendly.",
    "Support": "The support for this product is excellent.",
    "Warranty": "The warranty provided is very comprehensive.",
    "Maintenance": "This product requires minimal maintenance.",
    "Efficiency": "This product is very efficient.",
    "Portability": "This product is very portable.",
    "Aesthetics": "The aesthetics of this product are very pleasing.",
    "Sustainability": "This product is very sustainable.",
    "Technology": "The technology used in this product is cutting-edge.",
    "Craftsmanship": "The craftsmanship of this product is superb.",
    "Detail": "The attention to detail in this product is remarkable.",
    "Usability": "This product has excellent usability.",
    "Performance": "The performance of this product is exceptional.",
    "Durability": "This product is built to last.",
    "Innovation": "This product is very innovative.",
    "Simplicity": "This product is very simple to use.",
    "Flexibility": "This product is very flexible."
}

# Separator for theme strings
THEME_STRING_SEPARATOR = "\n"

# Final strings for the review text
FINAL_STRING = [
    "I would definitely recommend this product to others. It has exceeded all my expectations and I am extremely satisfied with its performance. The quality is top-notch and it offers great value for the price. I will definitely be buying this product again.",
    "I am very happy with my purchase. This product has made a significant difference in my daily routine. The design is sleek and modern, and it is very easy to use. I couldn't be happier with the results.",
    "This product has exceeded my expectations. The craftsmanship is superb and the attention to detail is remarkable. It is very durable and built to last. I am very impressed with its performance.",
    "I will definitely be buying this product again. It is a must-have for anyone looking for high quality and great value. The support provided is excellent and the warranty is very comprehensive. I am very pleased with my purchase.",
    "Overall, a fantastic product. The technology used is cutting-edge and the functionality is outstanding. It is very user-friendly and convenient to use. I am very satisfied with the results.",
    "I am extremely satisfied with this product. The aesthetics are very pleasing and the design is very appealing. It is very efficient and requires minimal maintenance. I would highly recommend it to others.",
    "This product is a must-have. It is very versatile and eco-friendly. The ingredients used are of high quality and the packaging is very secure. I am very happy with my purchase.",
    "I am very impressed with this product. The performance is exceptional and the reliability is unmatched. It is very safe to use and offers great value for the price. I couldn't be happier with the results.",
    "This product is worth every penny. The quality is outstanding and the value is remarkable. It is very comfortable to use and the design is very sleek. I am very pleased with my purchase.",
    "I couldn't be happier with this product. The results are amazing and the performance is top-notch. It is very easy to use and the support provided is excellent. I would definitely recommend it to others.",
    "This product is a game-changer. The innovation is remarkable and the functionality is outstanding. It is very user-friendly and convenient to use. I am very satisfied with the results.",
    "I am very pleased with this product. The quality is excellent and the value is great. It is very durable and built to last. I am very happy with my purchase.",
    "This product is of excellent quality. The craftsmanship is superb and the attention to detail is remarkable. It is very reliable and offers great value for the price. I would highly recommend it to others.",
    "I am very satisfied with this product. The performance is exceptional and the design is very appealing. It is very easy to use and the support provided is excellent. I am very pleased with the results.",
    "This product is highly recommended. The quality is outstanding and the value is remarkable. It is very versatile and eco-friendly. I am very happy with my purchase.",
    "I am very impressed with the results. The performance is top-notch and the reliability is unmatched. It is very safe to use and offers great value for the price. I would definitely recommend it to others.",
    "This product is a great investment. The quality is outstanding and the value is remarkable. It is very durable and built to last. I am very pleased with my purchase.",
    "I am very happy with the performance. The craftsmanship is superb and the attention to detail is remarkable. It is very efficient and requires minimal maintenance. I would highly recommend it to others.",
    "This product is top-notch. The innovation is remarkable and the functionality is outstanding. It is very user-friendly and convenient to use. I am very satisfied with the results.",
    "I am very pleased with the quality. The aesthetics are very pleasing and the design is very appealing. It is very efficient and requires minimal maintenance. I would highly recommend it to others.",
    "This product has made a significant difference. The performance is exceptional and the reliability is unmatched. It is very safe to use and offers great value for the price. I am very happy with my purchase.",
    "I am thrilled with this product. The quality is outstanding and the value is remarkable. It is very versatile and eco-friendly. I would definitely recommend it to others.",
    "This product is exceptional. The craftsmanship is superb and the attention to detail is remarkable. It is very durable and built to last. I am very pleased with my purchase.",
    "I am very content with my purchase. The performance is top-notch and the reliability is unmatched. It is very safe to use and offers great value for the price. I would highly recommend it to others.",
    "This product is fantastic. The innovation is remarkable and the functionality is outstanding. It is very user-friendly and convenient to use. I am very satisfied with the results.",
    "I am very pleased with the outcome. The quality is excellent and the value is great. It is very durable and built to last. I am very happy with my purchase.",
    "This product is superb. The craftsmanship is superb and the attention to detail is remarkable. It is very reliable and offers great value for the price. I would highly recommend it to others.",
    "I am very satisfied with the results. The performance is exceptional and the design is very appealing. It is very easy to use and the support provided is excellent. I am very pleased with my purchase.",
    "This product is amazing. The quality is outstanding and the value is remarkable. It is very versatile and eco-friendly. I am very happy with my purchase.",
    "I am very happy with the quality. The aesthetics are very pleasing and the design is very appealing. It is very efficient and requires minimal maintenance. I would highly recommend it to others.",
    "This product is outstanding. The performance is top-notch and the reliability is unmatched. It is very safe to use and offers great value for the price. I am very pleased with my purchase.",
    "I am very impressed with the craftsmanship. The quality is excellent and the value is great. It is very durable and built to last. I am very happy with my purchase.",
    "This product is a great buy. The innovation is remarkable and the functionality is outstanding. It is very user-friendly and convenient to use. I am very satisfied with the results.",
    "I am very pleased with the durability. The craftsmanship is superb and the attention to detail is remarkable. It is very reliable and offers great value for the price. I would highly recommend it to others.",
    "This product is highly effective. The performance is exceptional and the design is very appealing. It is very easy to use and the support provided is excellent. I am very pleased with my purchase.",
    "I am very satisfied with the performance. The quality is outstanding and the value is remarkable. It is very versatile and eco-friendly. I am very happy with my purchase.",
    "This product is a top choice. The innovation is remarkable and the functionality is outstanding. It is very user-friendly and convenient to use. I am very satisfied with the results.",
    "I am very happy with the value. The aesthetics are very pleasing and the design is very appealing. It is very efficient and requires minimal maintenance. I would highly recommend it to others.",
    "This product is a great investment. The performance is top-notch and the reliability is unmatched. It is very safe to use and offers great value for the price. I am very pleased with my purchase.",
    "I am very pleased with the design. The quality is excellent and the value is great. It is very durable and built to last. I am very happy with my purchase."
]
